name: CI of mc_naoqi_dcm with Docker

# This workflow checks the build-and-install script on base docker images

on:
  push:
    paths-ignore:
      # Changes to those files don't mandate running CI
      - ".gitlab-ci.yml"
      - ".jrl-ci"
      - ".github/workflows/package.yml"
      - "debian/**"
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu_20.04"]
        robot: ["nao", "pepper"] # robot
        version: ["2.5.0", "2.1.4"] # ctc toolchain version
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build with Docker (${{matrix.robot}} (ctc-toolchain version - ${{matrix.version}})
      run: |
        echo "::group::Setup Dockerfile"
        mkdir -p /tmp/mc_naoqi_dcm-docker
        cp -r `pwd` /tmp/mc_naoqi_dcm-docker/mc_naoqi_dcm
        cp .github/workflows/docker/Dockerfile_${{ matrix.version }} /tmp/mc_naoqi_dcm-docker/Dockerfile
        cd /tmp/mc_naoqi_dcm-docker
        sed -i -e 's/@ROBOT_NAME@/${{matrix.robot}}/g' Dockerfile
        echo "::endgroup::"
        echo "::group::Dockerfile used to build mc_naoqi_dcm"
        cat Dockerfile
        echo "::endgroup::"
        echo "::group::Build base image"
        docker build -t mc_naoqi_dcm-ci-${{matrix.version}}-${{matrix.robot}} .
        echo "::endgroup::"
        echo "::group::Copy built library"
        id=$(docker create mc_naoqi_dcm-ci-${{matrix.version}}-${{matrix.robot}})
        docker cp $id:/libmc_naoqi_dcm.so /tmp/libmc_naoqi_dcm_${{matrix.robot}}_${{matrix.version}}.so
        docker rm -v $id
        echo "::endgroup::"
    - name: Upload library as artefact (${{matrix.robot}} (ctc-toolchain version - ${{matrix.version}})
      uses: actions/upload-artifact@master
      with:
        name: libmc_naoqi_dcm_${{matrix.robot}}_${{matrix.version}}.so
        path: /tmp/libmc_naoqi_dcm_${{matrix.robot}}_${{matrix.version}}.so
