name: CI of mc_naoqi_dcm with Docker

# This workflow checks the build-and-install script on base docker images

on:
  push:
    paths-ignore:
      # Changes to those files don't mandate running CI
      - ".gitlab-ci.yml"
      - ".jrl-ci"
      - ".github/workflows/package.yml"
      - "debian/**"
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu_20.04"]
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build within Docker
      run: |
        echo "::group::Setup Dockerfile"
        mkdir -p /tmp/mc_naoqi_dcm-docker
        cp -r `pwd` /tmp/mc_naoqi_dcm-docker/mc_naoqi_dcm
        cp .github/workflows/docker/Dockerfile.${{ matrix.os }} /tmp/mc_naoqi_dcm-docker/Dockerfile
        cd /tmp/mc_naoqi_dcm-docker
        echo "::endgroup::"
        echo "::group::Dockerfile used to build mc_naoqi_dcm"
        cat Dockerfile
        echo "::endgroup::"
        echo "::group::Build base image"
        docker build -t mc_naoqi_dcm-ci-${{matrix.os}} .
        echo "::endgroup::"
        echo "::group::Copy built library"
        id=$(docker create mc_naoqi_dcm-ci-${{matrix.os}})
        docker cp $id:/libmc_naoqi_dcm.so /tmp/libmc_naoqi_dcm.so 
        docker rm -v $id
        echo "::endgroup::"
    - name: Upload build
      uses: actions/upload-artifact@master
      with:
        name: libmc_naoqi_dcm.so 
        path: /tmp/libmc_naoqi_dcm.so
    # - name: Slack Notification
    #   if: failure()
    #   uses: archive/github-actions-slack@master
    #   with:
    #     slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_TOKEN }}
    #     slack-channel: '#ci'
    #     slack-text: >
    #       [mc_naoqi_dcm] Build *${{ matrix.os }}* failed on ${{ github.ref }}
